services:
  qtoggleserver:
    image: qtoggle/qtoggleserver:${QTOGGLESERVER_VERSION}
    container_name: qtoggleserver
    restart: unless-stopped
    network_mode: host
    uts: host
    pid: host
    privileged: true
    environment:
      PYTHONPATH: /host/usr/lib/qtoggleserver/site-packages
    volumes:
      - /var/run/dbus/:/var/run/dbus/:z
      - /data/qtoggleserver:/data
      - /etc/qtoggleserver.conf.default:/usr/share/qtoggleserver/qtoggleserver.conf.sample
      - /etc/localtime:/etc/localtime
      - /usr/libexec/qtoggleserver/reboot:/sbin/reboot
      - /:/host
